# default network for the services is <project-name>_default
# volumes makes it so changes to the local files are pulled into the container without restarting
# - data exists on host at /var/lib/docker/volumes/todo_db_data/_data
#   - found with docker volume inspect --format '{{ .Mountpoint }}' todo_db_data
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env/development/web
      - .env/development/database
    environment:
      - SHAKAPACKER_DEV_SERVER_HOST=shakapacker_dev_server
  shakapacker_dev_server:
    build: .
    command: ./bin/shakapacker-dev-server
    ports:
      - "3035:3035"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/web
      - .env/development/database
    environment:
      - SHAKAPACKER_DEV_SERVER_HOST=0.0.0.0
  redis:
    image: redis
  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile-sidekiq
    command: ["bundle", "exec", "sidekiq"]
    env_file:
      - .env/development/web
      - .env/development/database


volumes:
  db_data:
  gem_cache: